<?php
/**
 * Implements hook_config_info().
 */
function nocurrent_pass_config_info() {
  $prefixes['nocurrent_pass.settings'] = array(
    'label' => t('Settings for nocurrent_pass'),
    'group' => t('No Current Pass'),
  );
  return $prefixes;
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function nocurrent_pass_form_user_admin_settings_alter(&$form, &$form_state) {
  // reorder fieldset weights
    $config = config('nocurrent_pass.settings');
  $form['nocurrent_pass'] = array(
    '#type' => 'fieldset',
    '#title' => t('Require Current Password'),
    '#weight' => -1,
    '#config' => 'nocurrent_pass.settings',    
  );
  $form['nocurrent_pass']['disabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Do not require current password'),
    '#description' => t('Check this box to disable the "current password" field on the User Edit form.'),
    '#default_value' => $config->get('disabled'),
     
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Remove the current password field from the user_profile_form form (user/%/edit).
 */
function nocurrent_pass_form_user_profile_form_alter(&$form, &$form_state) {
    $config = config('nocurrent_pass.settings');
    
  if ($config->get('disabled') == 1) {
    // searches the #validate array for the current_pass validation function, and removes it
    $key = array_search('user_validate_current_pass', $form['#validate']);
    if ($key !== FALSE) {
      unset($form['#validate'][$key]);
    }
    // hide the current password fields
    $form['account']['current_pass_required_value']['#access'] = FALSE;
    $form['account']['current_pass']['#access'] = FALSE;
 }
}